POST http://localhost:5000/user HTTP/1.1
Content-Type: application/json

{
    "firstName":"Savanna",
    "lastName":"Doe",
    "email":"SAVANNA.doe@gmail.com",
    "password":"qwerty123",
    "isSubscribed":true
}